### PR TITLE
Add all former eds and move list to the acknowledgements

### PR DESCRIPTION
**Pull request by mattgarrish**
As the title says.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/pull/2366.html" title="Last updated on Jul 23, 2022, 3:29 PM UTC (340db0c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/2366/319d4cb...340db0c.html" title="Last updated on Jul 23, 2022, 3:29 PM UTC (340db0c)">Diff</a>

### CODE REVIEW

**Comment by murata2makoto** [comment]
I am a bit sad not to see Markus's name here.

**Review by dauwhe — APPROVED** [review]

**Review by shiestyle — APPROVED** [review]

**Review by iherman — APPROVED** [review]

**Comment by iherman** [comment]
> I am a bit sad not to see Markus's name here.

You mean in the group? I agree... But his name does appear in the list of former editors (as it should).

**Comment by murata2makoto** [comment]
> > I am a bit sad not to see Markus's name here.
> 
> You mean in the group? I agree... But his name does appear in the list of former editors (as it should).

I overlooked it.

I had a look at EPUB 3.0 specifications.  Even if we eliminate CFIs (which are dropped from EPUB 3.3), two former editors (Elika J. Etemad and I) are missing.

P.S.  I overlooked Elika's name.

**Comment by mattgarrish** [comment]
> Even if we eliminate CFIs (which are dropped from EPUB 3.3)

This acknowledgements list is only for the core and reading systems specs, as these are brand new and combine the various releases of Publications/Packages, Content Docs, OCF, and Media Overlays plus the EPUB 3.2 spec. There are a lot of people to acknowledge, so having them all listed at the top is a bit of clutter, especially if it keeps growing with future releases.

You're still acknowledged in the former editor's list at the top of the Overview, @murata2makoto, along with the others that worked on it, as has not been absorbed. The same is true for the former editors of CFI and Multiple Renditions.

Sorry if that wasn't clear.

I can add some additional prose that it's for the combined specs if that'll help. Something like:

> the former editors of the EPUB 3 specifications that were merged to make this document:

**Comment by mattgarrish** [comment]
Or we can drop the former editors from the overview and use this acknowledgements for it, too, plus @murata2makoto

**Comment by iherman** [comment]
> Or we can drop the former editors from the overview and use this acknowledgements for it, too, plus @murata2makoto

Let us do this for the overview, too.

**Comment by murata2makoto** [comment]
Sorry.  I did not understand that we also have "EPUB 3.3 Overview".  I will raise a separate issue about that.

My name was listed as an editor in the original "EPUB 3 Overview", not because I contribute to editing the document, but because I contributed to the global language support of EPUB 3.  

>Or we can drop the former editors from the overview and use this acknowledgements for it, too, plus @murata2makoto

I would be honored.

**Pull request merged**
