### PR TITLE
Updated the term description for EPUB Creator (Issue 2216)

### LINKED ISSUE #2216: "EPUB Creators MUST" and "EPUB Creators SHOULD" in EPUB A11Y 1.1
EPUB A11Y 1.1 has several sentences beginning with "EPUB Creators MUST" or "EPUB Creators SHOULD". I propose to reformulate them as requirements on EPUB publications rather than those on humans.

First, the scope of EPUB A11Y 1.1 is the accessibility and discoverability of EPUB Publications.  Humans are outside the scope.

Second, it is not possible to create tests for these sentences.  Ace does not check EPUB creators either.

Third, these sentences do not impose any requirements on EPUB publications, since programs or other users are not prohibited from changing what EPUB creators did.

3.4.1.3.1 PAGINATION SOURCE

The 1st para, "Meeting this Objective"

> EPUB Creators MUST identify that source in the Package Document metadata.

Reformulate the above sentence.

3.4.1.3.2 PAGE LIST

The 2nd para, in "Meeting this Objective"

> EPUB Creators SHOULD ....

Ditto.

The 3rd para, in "Meeting this Objective"

>EPUB Creators should

Is this just a non-normative sentence?  (Note: "should" rather than "SHOULD" here).

3.4.1.3.3 Page Breaks

The 2nd para, "Meeting this Objective"

>they SHOULD include page break markers for ....

What is the subject ("they")?  It cannot be "an EPUB Creator" since it is singular.  Reformulate this sentence without using "EPUB creator" as the subject.

> they should include

Is this just a non-normative sentence?  (Note: "should" rather than "SHOULD" here).

The last para, "Meeting this Objective"

> EPUB Creators MUST identify the page numbers in the markup that controls the playback.

Reformulate the above sentence.

3.4.2.3.1 COMPLETENESS

1st para, "Meeting this Objective"

>  EPUB Creators MUST provide synchronized audio playback via Media Overlays for all textual content.

Reformulate the above sentence.

3.4.2.3.2 Reading Order

Ths 1st para, "Meeting this Objective"

 > EPUB Creators SHOULD ...

Reformulate the above sentence.

3.4.2.3.3 Skippability

The 1st para, "Meeting this Objective"

>  EPUB Creators SHOULD ...

Reformulate the above sentence.

3.4.2.3.4 Escapability

The 1st para, "Meeting this Objective"

> EPUB Creators SHOULD ...

Reformulate the above sentence.

3.4.2.3.5 Navigation Document

The 1st para, "Meeting this Objective"

> EPUB Creators SHOULD ...

Reformulate the above sentence.

3.3.2.1 Page and Publication

> EPUB Creators MUST evaluate their accessibility as part of the larger work.

Reformulate the above sentence.

> EPUB Creators MUST evaluate the WCAG guidelines for content to be ...

Reformulate the above sentence.

3.3.2.2 Applying the Conformance Criteria

> EPUB Creators MUST NOT use EPUB's fallback mechanisms to provide a conforming alternate version [WCAG2], ...

Here is my proposal.

  Every EPUB and Foreign Content Document in the spine plane (i.e., either in the spine element or in the fallbackchain) MUST meet the conformance requirements of the level claimed.

3.5.2 Publication Conformance

There are four occurrences of "EPUB Creators MUST".  All of them should be reformulated.

Here is my proposed rewrite for the first one.

Values matching the pattern A11Y-VER indicate the version number of the EPUB Accessibility specification the publication conforms to, not including the decimal points.  The value "11" indicates conformance to this version of this specification.

### PR DESCRIPTION
**Pull request by iherman**
This is a proposal to move ahead on issue #2216, adopting the 
[proposal of Matt](https://github.com/w3c/epub-specs/issues/2216#issuecomment-1090734556).

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/pull/2234.html" title="Last updated on Apr 8, 2022, 12:24 PM UTC (27f96f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/2234/1287600...27f96f7.html" title="Last updated on Apr 8, 2022, 12:24 PM UTC (27f96f7)">Diff</a>

### CODE REVIEW

**Review by mattgarrish — APPROVED** [review]
LGTM. I don't have anything more to add to it this morning.

**Review by wareid — APPROVED** [review]

**Comment by iherman** [comment]
@murata2makoto is this o.k. for you as an intermediate measure to handle #2216?

**Comment by murata2makoto** [comment]
@iherman 

> @murata2makoto is this o.k. for you as an intermediate measure to handle https://github.com/w3c/epub-specs/issues/2216?

I am not against this change, although I would like to keep #2216 open.

**Comment by mattgarrish** [comment]
I've removed the tag to close #2216, but we should probably switch that issue to deferred. That's the kind of change better raised/addressed at the beginning of a revision than the end so that the changes get looked at over and over during the course of updating the specifications.

**Comment by iherman** [comment]
> I've removed the tag to close #2216, but we should probably switch that issue to deferred. That's the kind of change better raised/addressed at the beginning of a revision than the end so that the changes get looked at over and over during the course of updating the specifications.

+1. I have changed the labels for the issue.

**Comment by iherman** [comment]
This was discussed during the [pmwg meeting on 25 September 2025](https://w3c.github.io/pm-wg/minutes/2025-09-25.html#e1d0).

<details><summary><i>View the transcript</i></summary>

<h3>Issue #2216 - <a href="https://github.com/w3c/epub-specs/issues/2216" rel="noopener noreferrer">w3c/<wbr>epub-specs#2216</a></h3>
<p><cite>&lt;wendyreid&gt;</cite> <a href="https://github.com/w3c/epub-specs/pull/2234" rel="noopener noreferrer">w3c/<wbr>epub-specs#2234</a></p>
<p><cite>wendyreid:</cite> Issue 2216 this is concerning language we use to describe creators may be a little to narrow</p>
<p><cite>mgarrish:</cite> I think people are not confused about the difference between "must" and "epub creators must set it"<br>
<span>… we don't really have the time to rewrite all of the specifications when the issue was raised</span><br>
<span>… how much time will this take vs the benefits it will bring</span></p>
<p><cite>duga:</cite> I agree with mgarrish, I don't think anyone will notice and this change won't improve any ebooks<br>
<span>… at the same time, the language is wrong, and it bugs me</span><br>
<span>… we don't care if the creator adds the metadata, we just want to be sure it is there</span><br>
<span>… but on the other hand, no one has ever gotten this wrong</span></p>
<p><cite>gautierchomel:</cite> I see confusion about who is the "creator" when I am doing trainings.<br>
<span>… I would like to see that addressed</span><br>
<span>… I think it would be worth the work</span></p>
<p><cite>AvneeshSingh:</cite> can we do this in EPUB 3.4 or not?</p>
<p><cite>wendyreid:</cite> or can we do this in Accessibiliy 1.2</p>
<p><cite>AvneeshSingh:</cite> can we take this on in the time frame we have?</p>
<p><cite>wendyreid:</cite> we haven't seen confusion in the past, but we may see it in the future<br>
<span>… we spend a lot of time with the spec, but most people rely on the tools or the trainings</span><br>
<span>… as long as those are clear, is this really required</span></p>
<p><cite>mgarrish:</cite> the problem hasn't been in how we word things<br>
<span>… the definition of "epub creator" is more the problem</span><br>
<span>… maybe there is a compromise in looking at that definition rather than rewriting all the specifications</span></p>
<p><cite>duga:</cite> You just made a good case for rewriting it<br>
<span>… we've spent years trying to define "creator"</span><br>
<span>… maybe we should try to get rid of it</span><br>
<span>… but because of the timeline, maybe we just defer this again until epub accessibility 1.3</span></p>
<p><cite>mgarrish:</cite> maybe we start with the accessibility specs and see how much is involved<br>
<span>… then if it is too complex we can dump out of it</span></p>
<p><cite>wendyreid:</cite> I like that approach. Try in the accessibility document first<br>
<span>… to see how hard it is to make the change</span><br>
<span>… see how useful it is in 1.2 and abandon it if it is too hard</span></p>
<p><cite>mgarrish:</cite> I don't mind taking a stab at this and seeing how it goes</p>

<hr /></details>

**Pull request merged**
