### PR TITLE
Add dedication to Ben Schroeter

### PR DESCRIPTION
**Pull request by mattgarrish**
Adds a new acknowledgements file for the accessibility spec along with the dedication.

- [preview](https://cdn.statically.io/gh/w3c/epub-specs/a11y/add-dedication/epub33/a11y/index.html)
- [diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://w3c.github.io/epub-specs/epub33/a11y/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://cdn.statically.io/gh/w3c/epub-specs/a11y/add-dedication/epub33/a11y/index.html)

### CODE REVIEW

**Review by dauwhe — APPROVED** [review]

**Comment by mattgarrish** [comment]
I just remembered I didn't update the preview/diff links in the first message (copied from another pull request). They should work correctly now.

**Review by iherman — CHANGES_REQUESTED** [review]
I am absolutely +1 with the paragraph about Ben.

However, the current acknowledgement list, ie, the list of WG members, is out of date. What should be done, instead, is to create a new file `epub33/common/ack-script/acknowledgement-a11y-dedication.html` with the new paragraph (using the pattern of `epub33/common/ack-script/acknowledgement-dedication.html`) and the generation script should be run to regenerate the included file. I am happy to run the script, of course.

Merging the current version of the spec is not really useful, it will be changed as soon as the new inclusion files are there...

**Review by iherman — APPROVED** [review]
Actually... I realized that the repo was not matt's, so I could do all this myself... I have

- added the required new dedication pattern to Ben
- regenerated _all_ acknowledgement files, which means that a PR merge will produce a new version of a number of notes, too (which is all right). But things are now up-to-date

**Comment by mattgarrish** [comment]
Thanks, LGTM!

**Review by shiestyle — APPROVED** [review]

**Review by wareid — APPROVED** [review]

**Comment by iherman** [comment]
@gregoriopellegrino @GeorgeKerscher @avneeshsingh @clapierre, as "core" contributors to the a11y documents, any objections to merge this PR?

**Comment by GeorgeKerscher** [comment]
I think we should merge it.

**Comment by mattgarrish** [comment]
As far as I know, we're still waiting on an issue with the copyright line to be fixed @GeorgeKerscher. Until then, I think any merge attempts will fail to publish in the backend system. I'll get this merged once I get the green light from @iherman.

**Comment by mattgarrish** [comment]
Sorry, I missed that Ivan asked if you're okay to merge. I'll still let him figure out when to do it.

**Comment by iherman** [comment]
> As far as I know, we're still waiting on an issue with the copyright line to be fixed @GeorgeKerscher. Until then, I think any merge attempts will fail to publish in the backend system. I'll get this merged once I get the green light from @iherman.

Yes, it is probably better to wait for the copyright issue to be solved before we merge this (the Rec-track documents would be fine because the automatic publishing is switched off anyway but this merge would also affect a bunch of notes). But the promise was to settle that this week, so we should be in the clean as soon as doable.

Thanks for the approval, @GeorgeKerscher

**Review by gregoriopellegrino — APPROVED** [review]

**Review by dauwhe — APPROVED** [review]

**Pull request merged**
