### PR TITLE
Fix wg metadata

### PR DESCRIPTION
**Pull request by mattgarrish**
Only for the three rec-track specs.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/pull/2576.html" title="Last updated on Jul 25, 2023, 6:29 PM UTC (d12b913)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/2576/0dd3160...d12b913.html" title="Last updated on Jul 25, 2023, 6:29 PM UTC (d12b913)">Diff</a>

### CODE REVIEW

**Review by iherman — APPROVED** [review]

**Comment by mattgarrish** [comment]
So does this qualify as a class 2 change, too, since we're modifying the text of the specifications? (i.e., I assume I can't just merge this, either.)

**Comment by mattgarrish** [comment]
In other words, should this PR only update the core and a11y specs because those are the only two we're updating with the other issues, and the RS spec would change it's metadata whenever we have some other change for it?

**Comment by iherman** [comment]
> So does this qualify as a class 2 change, too, since we're modifying the text of the specifications? 

I think so

> (i.e., I assume I can't just merge this, either.)

I do not think so. I believe any merge for rec track should have a more "visible" approval from the WG, or at least from the WG Chairs

cc @w3c/w3c-group-145018-members

**Comment by mattgarrish** [comment]
I'm going to close and re-open this for the two specs we're updating. Seems some unrelated changes got in an earlier commit, and undoing is proving a pain.

**Pull request closed without merging**
