### PR TITLE
Add anchors and data-tests to match w3c/epub-tests#22

### PR DESCRIPTION
**Pull request by dlazin**
Add anchors and data-tests to match https://github.com/w3c/epub-tests/pull/22.

### CODE REVIEW

**Review by iherman — APPROVED** [review]

**Comment by iherman** [comment]
I think having these test references is great, so we should go ahead with the respec approach. But I wonder whether we can come up with some extra CSS tricks to make those references a bit less emphasized. At the moment the reference is in bold, put on a separate line; a bit obtrusive for my taste. Can we find something a bit better (e.g., put it at the end of the previous paragraph in brackets and not in bold, something like that)? 

As an alternative we may come up with a small piece of javascript and a corresponding button at the start of the file which makes these references' visibility on and off. There are other specs that do such tricks...

(My concern is that these references break the reading flow of the text.)

**Comment by iherman** [comment]
Hm. Actually... it looks like the generated `<details>` element for the tests only appear when the document runs respec. In other words, if I generate a 'final' HTML file (which also means when we publish an 'official' document on /TR) then these elements do not appear in the generated output.

@marcoscaceres is that correct and is this the intention? If that is the case then my comment above becomes moot; as long as these entries help us to keep track of the relevant tests, but do not bother the reader of the final spec, we are probably fine.

**Comment by marcoscaceres** [comment]
> @marcoscaceres is that correct and is this the intention? If that is the case then my comment above becomes moot; as long as these entries help us to keep track of the relevant tests, but do not bother the reader of the final spec, we are probably fine.

Yes, that is correct - they only show up in the "dynamic" version of the document. We remove them when the document is exported.

**Comment by iherman** [comment]
> > @marcoscaceres is that correct and is this the intention? If that is the case then my comment above becomes moot; as long as these entries help us to keep track of the relevant tests, but do not bother the reader of the final spec, we are probably fine.
> 
> Yes, that is correct - they only show up in the "dynamic" version of the document. We remove them when the document is exported.

That makes a lot of sense.

@dlazin then, as far as I am concerned, it is a go... :-)

**Pull request merged**
