### PR TITLE
changed media queries reference

### PR DESCRIPTION
**Pull request by iherman**
In specref the (old) reference to media queries level 3 is marked as 'aliased' to css3-mediaqueries. But the generated code by respec does not seem to understand this 'alias', and this leads to a wrong fragment reference (and link checker complain).

I exchanged the reference to the 'official' one.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 6, 2022, 1:13 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fepub-specs%2Fb16ea9a1573c0e9879156723ba520198ee3a0088%2Fepub33%2Fcore%2Findex.html%3FisPreview%3Dtrue)

```

😭  Sorry, there was an error generating the HTML. Please report this issue!
Specification: http://labs.w3.org/spec-generator/uploads/o7ZETJ?isPreview=true&publishDate=2022-05-06
ReSpec version: 32.1.6
File a bug: https://github.com/w3c/respec/
Error: Error: Evaluation failed: Timeout: document.respec.ready didn't resolve in 27514ms.
    at ExecutionContext._evaluateInternal (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:221:12)
    at async toHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:92:18)
    at async Object.generate [as respec] (file:///u/spec-generator/generators/respec.js:15:44)
    at async file:///u/spec-generator/server.js:244:48

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/epub-specs%232262.)._
</details>

### CODE REVIEW

**Comment by iherman** [comment]
Not to be merged before the CR is out!!!

**Comment by mattgarrish** [comment]
I'm not sure this is the right solution, as the shortname is now "mediaqueries-3" for the most recently released recommendation: https://www.w3.org/TR/mediaqueries-3/

It's the use of an alias to map to the old shortname that appears to have broken specref. See the issue I opened here: https://github.com/tobie/specref/issues/706

Changes to W3C specs haven't been recorded for a month now, which means our CR docs won't be referenced after the CR is published until specref gets fixed (i.e., the references will still refer to the specs as Working Drafts).

**Comment by iherman** [comment]
> I'm not sure this is the right solution, as the shortname is now "mediaqueries-3" for the most recently released recommendation: [w3.org/TR/mediaqueries-3](https://www.w3.org/TR/mediaqueries-3/)
> 

I try to be pragmatic and take what works...

> Changes to W3C specs haven't been recorded for a month now, which means our CR docs won't be referenced after the CR is published until specref gets fixed (i.e., the references will still refer to the specs as Working Drafts).

Sigh. If that indeed happens, I believe this is where sysreq will have to intervene. Otherwise we will have to have to use our own biblio files to get at least our stuff right, which is crazy.

Cc @deniak

**Comment by deniak** [comment]
> Sigh. If that indeed happens, I believe this is where sysreq will have to intervene. Otherwise we will have to have to use our own biblio files to get at least our stuff right, which is crazy.
>
> Cc @deniak

I'll try to see what I can do but I have almost no knowledge of how specref works and how the spec generators uses it.

**Comment by mattgarrish** [comment]
I tried my best to help fix it with this PR https://github.com/tobie/specref/pull/707

But I don't know know enough about the internals to understand why it wouldn't work, so I closed it off.

**Comment by mattgarrish** [comment]
The problem has been fixed in https://github.com/tobie/specref/pull/709

Closing this as the reference should be mediaqueries-3.  mediaq and css3-mediaqueries are now aliased to the new shortname.

**Pull request closed without merging**
