### PR TITLE
Illustrations for the Package Rendering Vocabulary

### LINKED ISSUE #1314: Include some illustrations in Package Rendering Metadata
We should have some illustrations of  these very visual properties, as a way of making the spec more understandable.

### PR DESCRIPTION
**Pull request by iherman**
This is an attempt to answer to the request in #1314. 

The PR is not yet complete; in particular, an alt text should be created for all four illustrations (help would be welcome on that one). But I wanted to get it out there to see if the general direction is o.k.

Fix #1314.

See [preview](https://raw.githack.com/w3c/epub-specs/figures-rendering-metadata/epub33/core/index.html#app-rendering-vocab)

(Not sure why the usual preview didn't work...)

### CODE REVIEW

**Review by dauwhe — APPROVED** [review]
Lovely! Thanks!

**Review by wareid — APPROVED** [review]

**Review by mattgarrish — APPROVED** [review]

**Comment by iherman** [comment]
@dauwhe this was a bit premature... there are issues with the new automatic editing that leads to problems...

@mattgarrish I will push a version to PR without the object element and merge that one so that the core spec gets in sync again

**Comment by dauwhe** [comment]
Sorry I got carried away :)

**Comment by iherman** [comment]
No problems. I have taken care of the issue now. I still have to add some alt text to the images, but that can be done later in a separate PR

**Pull request merged**
