### PR TITLE
OCF Fixes

### LINKED ISSUE #1329: Clarify reading system / ocf processor
There's a sometimes confusing mix of these two terms in OCF. There are reading system requirements, but often the requirements themselves reference what OCF processors have to do.

Might be helpful to drop OCF processor as a term and simply add a note/section that explains that an application that is not handling the container for rendering purposes (i.e., is not a full-fledged reading system) can ignore any related requirements.

### LINKED ISSUE #1337: Reading systems not required to follow abstract container rules
Another oddity I noticed in the extracted requirements is that for OCF only the zip container and obfuscation sections are mentioned in the [top-level requirements](https://w3c.github.io/publ-epub-revision/epub33/rs/#ocf-conformance-rs). The abstract container section also lists a number of reading system requirements, but there's no corresponding bullet to follow them.

### PR DESCRIPTION
**Pull request by mattgarrish**
This PR fixes #1329 and fixes #1337 with primarily editorial changes:

- It switches the uses of "OCF Processor" to "Reading System" and instead adds a note to the top-level conformance section that an application that processes OCF containers does not have to be a full-fledged reading system, in which case any rendering requirements don't apply.
- It adds the missing bullet for abstract container requirements

[Reading Systems preview](https://raw.githack.com/w3c/publ-epub-revision/fix/issues-1329-1337/epub33/rs/)
[Reading Systems diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fpubl-epub-revision%2Fepub33%2Frs%2F&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fraw.githack.com%2Fw3c%2Fpubl-epub-revision%2Ffix%2Fissues-1329-1337%2Fepub33%2Frs%2Findex.html)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/publ-epub-revision/pull/1343.html" title="Last updated on Oct 13, 2020, 1:55 PM UTC (e9582bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/publ-epub-revision/1343/82f0f34...e9582bf.html" title="Last updated on Oct 13, 2020, 1:55 PM UTC (e9582bf)">Diff</a>

### CODE REVIEW

**Review by iherman — APPROVED** [review]
YES! It reduces the confusion when reading the stuff...

**Comment by murata2makoto** [comment]
The term processor is still used in "when creating a conforming processor."

**Comment by mattgarrish** [comment]
> The term processor is still used in "when creating a conforming processor."

Right, but that's only the generic sense of the word (i.e., something that can process the zip file). It might be good to remove "conformant" and tie it back to the first sentence by rewording to: "when creating such a processor"

**Comment by mattgarrish** [comment]
Changed in https://github.com/w3c/publ-epub-revision/commit/259604676418fe9d973c22ba3d716a3ba359b065#

**Comment by mattgarrish** [comment]
Actually, everything after "ignored" is redundant since the sentence already begins with "in these cases": https://github.com/w3c/publ-epub-revision/commit/9c931e5b142c72ffd8c41ef7354ff6164ae22aaf

**Pull request merged**
