### PR TITLE
Add note about other scripting contexts

### LINKED ISSUE #2098: Scripted SVG
I was just asked a question about embedding scripted svg and couldn't decipher exactly what is valid from the specification.

It's clear that you can have a scripted Top-Level SVG Content Document. And we say that an SVG with script referenced from an HTML iframe element is container-constrained.

But what happens in other cases? Can you embed an SVG with scripting using `object` or is that invalid? Can you embed an SVG with scripting in `img` even though the scripting won't work, or should that be reported as invalid?

### PR DESCRIPTION
**Pull request by mattgarrish**
Best place I could find for the note is right after we first define the top-level and container-constrained scripting contexts.

Fixes #2098

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/pull/2136.html" title="Last updated on Mar 30, 2022, 9:25 AM UTC (1709136)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/2136/7e81268...1709136.html" title="Last updated on Mar 30, 2022, 9:25 AM UTC (1709136)">Diff</a>

### CODE REVIEW

**Review by iherman — COMMENTED** [review]
Is it the intention that we leave the issue of whether, conceptually, a script in SVG via object is considered to be spine level or not, open? Because this how I read this note.

My higher level impression is that a container level script has some restrictions (no dom or window size modification) whether for spine level scripts anything goes. In this respect, I do not see a problem saying that, conceptually, a script we are talking about may be viewed spine level...

**Comment by mattgarrish** [comment]
> a script in SVG via object is considered to be spine level or not

It's not technically the same as a spine-level script as a spine-level script doesn't have a parent it can manipulate. It's a container-constrained script that isn't constrained by its container, I guess.

That's the only way I can read this RS spec requirement:

> Reading Systems MAY support scripting in other contexts, but this specification does not address such scripting.

So there are no defined constraints on what an SVG referenced from an `object` can do, and no requirement that scripting be supported.

**Comment by iherman** [comment]
> container-constrained script that isn't constrained by its container

:-)

I guess we can just leave it as is then...

**Review by iherman — APPROVED** [review]

**Comment by iherman** [comment]
Minor knit, the [section on container-constrained, ie, §3.3.2.2.1](https://w3c.github.io/epub-specs/epub33/core/#sec-scripted-container-constrained) also used the 'parent' terminology that we located elsewhere and replaced by 'host'. Maybe it is a good time to change it...

**Pull request merged**
