### PR TITLE
Add webp to image core media types

### LINKED ISSUE #1344: Add WebP as a core format
[In our current EPUB 3.x charter](https://www.w3.org/2020/08/epub-wg-charter.html#scope:~:text=new%20media%20types%2C%20such%20as%20OPUS%2C%20BPG%2C%20or%20WebP), WebP is clearly identified as a candidate for our list of core formats.

Now that Apple has released iOS 14, WebP support is finally available on all major modern browsers: https://caniuse.com/webp

WebP has many benefits over JPEG and PNG and while AVIF might eventually become a better option, it's probably a few years away from being widely adopted.

### PR DESCRIPTION
**Pull request by mattgarrish**
I'm not 100% sure on the citing for this. There are a couple of google developer pages for the container and lossless bitstream specifications, so I added both. Are these formal enough references for W3C @iherman? (I don't see what else we could cite, though.)

Partially addresses #1344. Issue of a reliable source specification still to be determined.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/pull/1347.html" title="Last updated on Nov 6, 2020, 8:08 PM UTC (d2bef44)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/1347/706855e...d2bef44.html" title="Last updated on Nov 6, 2020, 8:08 PM UTC (d2bef44)">Diff</a>

### CODE REVIEW

**Review by HadrienGardeur — APPROVED** [review]

**Review by wareid — APPROVED** [review]

**Review by iherman — CHANGES_REQUESTED** [review]
@mattgarrish is right that the WebP normative references are iffy. See my comment in https://github.com/w3c/publ-epub-revision/issues/1344#issuecomment-710028776.

Until this is resolved, we should not merge this imho.

**Comment by dauwhe** [comment]
I'm trying to shame Google on Twitter about this :)

**Comment by dauwhe** [comment]
It appears that the developer is [not interested](https://twitter.com/PascalMassimino/status/1317887675794411520) in standardization:

> The specs used a reference are:
lossy VP8: https://tools.ietf.org/html/rfc6386
> + Lossless: https://developers.google.com/speed/webp/docs/webp_lossless_bitstream_specification
> + Container: https://developers.google.com/speed/webp/docs/riff_container

> The (large) time investment it takes  going to ISO or similar for official spec was diverted to making libwebp better :)

They do not address the question of registering the media type. Is that possible without a specification from a standards body?

**Comment by iherman** [comment]
See https://github.com/w3c/publ-epub-revision/issues/1344#issuecomment-711689698. I propose to keep this PR open and discuss the more general issue.

**Comment by svgeesus** [comment]
That is just handwaving.

If there is a decent enough specification then it is trivial to register a Media Type.

I offered to help registering it.

**Comment by iherman** [comment]
> I offered to help registering it.

Thank you @svgeesus

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-06-epub#section5).

- `RESOLVED:  Merge #1347 with an additional warning about support for WebP`
<details><summary><i class="differentiate">View the transcript</i></summary>
Issue on WebP<br/>
Wendy Reid: <a href="https://github.com/w3c/epub-specs/pull/1347">https://github.com/w3c/epub-specs/pull/1347</a><br/>
Wendy Reid: I thought we were waiting for an answer from someone<br/>
Ivan Herman: perhaps in a non-normative fashion<br/>
… it’s not registered anywhere<br/>
Dave Cramer: When we were talking about WebP, it’s an internal doc at Google<br/>
… the person who wrote the spec didn’t want to register the media type<br/>
… various W3C people have offered to help register the type<br/>
… some concern that google could change the spec<br/>
Wendy Reid: Chris Lilley had offered to help with media type registration<br/>
Ivan Herman: what we could do is… we can do two things<br/>
… one, keep the PR open and come back in a year<br/>
… two, we put it in with a big yellow warning saying this is a feature that may be taken out<br/>
… because status is unclear<br/>
… I don’t know which of the two is better<br/>
Dave Cramer: I would be curious to see if WebP works in existing reading systems<br/>
Hadrien Gardeur: It works in readium<br/>
Ivan Herman: does it rely on google engine?<br/>
Hadrien Gardeur: Whatever is around, if you’re on iOS 14 it works there, on android it has worked for a few years<br/>
… has worked on Android for a while<br/>
Ivan Herman: what about thorium?<br/>
Hadrien Gardeur: Thorium uses chromium, so it works, even on a mac<br/>
Ivan Herman: even on a mac?<br/>
Hadrien Gardeur: yes<br/>
… I would expect it would work in a lot of places, because it’s supported by many webviews<br/>
… probably won’t work on RMSDK<br/>
Garth Conboy: I agree with Dave and Hadrien<br/>
… I think we should put it in with a warning<br/>
… that might drive more learning<br/>
Matt Garrish: a third option is reconsider mandating support in the spec<br/>
… there are custom implementations, we need a baseline… I don’t know if that’s something the spec needs to say<br/>
… and not getting into the whole restricting things that are outside of our control<br/>
… that’s a separate discussion<br/>
Wendy Reid: I support putting in WebP with a warning<br/>
Ivan Herman: to follow up on what matt said<br/>
… we are already in an awkward situation<br/>
… there are some media types where we are explicit<br/>
… we don’t have a list of video types<br/>
Dave Cramer: Difference between video and images, 99% of EPUBs have images, but very few EPUBS have video<br/>
George Kerscher: I would love to see us start testing video in the titles<br/>
… people are waiting for that quality of content being added to educational materials<br/>
… putting it in the spec would protect from Google IP<br/>
Hadrien Gardeur: ivan hinted at the larger question<br/>
… can we tackle that larger question?<br/>
… I don’t think it’s sustainable<br/>
… it belongs in a best practices doc<br/>
… we are not consistent with how we deal with HTML/CSS vs images<br/>
Gregorio Pellegrino: for the image format I’m concerned about e-readers<br/>
… there are a lot of old e-readers which would never support webp<br/>
… and new content wouldn’t work<br/>
Garth Conboy: I would like to get to Hadrien’s discussion<br/>
… we can have a vote now about WebP<br/>
… then return to the larger issue<br/>
… should we move image specificity to video specificity<br/>
Ivan Herman: garth almost said what I wanted to say<br/>
… let’s decide on webp today<br/>
… and open an issue on github<br/>
Proposed resolution: Merge #1347 with an additional warning about support for WebP (Wendy Reid)<br/>
Ivan Herman: +1<br/>
Garth Conboy: +1<br/>
Matt Garrish: +1<br/>
George Kerscher: +<br/>
Hadrien Gardeur: +1<br/>
Bill Kasdorf: +1<br/>
Charles LaPierre: +1<br/>
Juliette McShane: +1<br/>
Gregorio Pellegrino: 0<br/>
Brady Duga: 0<br/>
Wendy Reid: +1<br/>
Matthew Chan: 0<br/>
George Kerscher: I think it’s great if we put this in<br/>
Toshiaki Koike: 0<br/>
Laurent Le Meur: +1<br/>
George Kerscher: if it moves to a best practice that’s fine<br/>
Ben Schroeter: 0<br/>
Masakazu Kitahara: 0<br/>
George Kerscher: but we get the format into implementations and documented<br/>
Wendy Reid: that’s another discussion<br/>
Resolution #2: Merge #1347 with an additional warning about support for WebP<br/>
</details>

**Comment by iherman** [comment]
The latest information is that WebP will move to IETF in the coming months. We can have good hope that, by the time the spec is final, the issues around WebP will be gone.

@dauwhe @shiestyle @wareid @HadrienGardeur

**Pull request merged**
