### PR TITLE
Add index to core spec

### LINKED ISSUE #2260: Index for spec?
In the EPUB 3.3 Webinar hosted by Booknet Canada, someone asked why the spec didn't have an index. It's a good question. I know that some other W3C specs do have indexes. Can ReSpec help with this?

### PR DESCRIPTION
**Pull request by mattgarrish**
Adds the respec-generated index of terms. I don't think this is useful for any of the other specs as they don't add similar numbers of new terms.

Fixes #2260

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 17, 2022, 11:44 AM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fepub-specs%2F452a1385184e18cc485e6f48ae30addb72d41c0a%2Fepub33%2Fcore%2Findex.html%3FisPreview%3Dtrue)

```

😭  Sorry, there was an error generating the HTML. Please report this issue!
Specification: http://labs.w3.org/spec-generator/uploads/KfgrHj?isPreview=true&publishDate=2022-05-17
ReSpec version: 32.1.6
File a bug: https://github.com/w3c/respec/
Error: Error: Evaluation failed: Timeout: document.respec.ready didn't resolve in 27763ms.
    at ExecutionContext._evaluateInternal (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:221:12)
    at async toHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:92:18)
    at async Object.generate [as respec] (file:///u/spec-generator/generators/respec.js:15:44)
    at async file:///u/spec-generator/server.js:244:48

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/epub-specs%232288.)._
</details>

### CODE REVIEW

**Comment by mattgarrish** [comment]
Can be previewed here: https://raw.githack.com/w3c/epub-specs/feature/add-index/epub33/core/index.html#index

**Review by iherman — APPROVED** [review]
Overall, I think it is worth adding it, even if not perfect.

One tiny thing. The generated code seems to be:

```html
<a class="index-term" href="....">
    "container resource"
</a>
```

for elements and then

```html
<a class="index-term" href="....">
    <code>meta</code>
</a>
```

for elements. Would it be better if we added to our css something like

```css
a.index-term code {
   color: #c63501 !important;
}
```

we use that colour all over the place for code, better keep it in the index, too...

**Comment by mattgarrish** [comment]
> Would it be better if we added to our css

Should this be raised against respec?

It's respec that colours the code tags in the body, so if we manually override the index then we have to keep watch that the respec css doesn't change in the future.

**Comment by iherman** [comment]
> > Would it be better if we added to our css
> 
> Should this be raised against respec?
> 
> It's respec that colours the code tags in the body, so if we manually override the index then we have to keep watch that the respec css doesn't change in the future.

Oops, somehow I always thought that we set the color, not respec...

Yes, that should be a respec issue. Not only for this case; I have added the following entries to our common css files to ensure the right colour when using xref:

```css
code a[data-type~="element"], 
code a[data-type~="dfn"],
code a[data-type~="element-attr"]
{
    color: #c63501 !important;
}
```

These should be superfluous as well.

Do we want to start by setting it for ourselves and raise an issue afterwards, or just raise an issue? I would be in favour of the former; I do not know whether such an issue would be taken care of with high priority...

**Comment by mattgarrish** [comment]
> Do we want to start by setting it for ourselves and raise an issue afterwards

That works for me. I'll update the PR when I have a minute.

**Comment by iherman** [comment]
Also: do we want to switch indexing on for RS? It does not define many new concepts, but I also found the generated list of external concept references useful... (I cannot judge the value for the A11y document).

**Comment by mattgarrish** [comment]
> > Do we want to start by setting it for ourselves and raise an issue afterwards
> 
> That works for me.

Although, looking at the result of adding custom CSS, I'm not so sure it's a good idea. Linked code is now hard to distinguish from unlinked code as there may only be a faint dotted underline. We also get links that are part orangey-red and part blue if they include a code-tagged word with other words. It's really quite messy. It might be better to remove the custom CSS and figure out with the respec/spec-prod folks what should be done.

**Comment by mattgarrish** [comment]
> It does not define many new concepts, but I also found the generated list of external concept references useful...

I'm of the opposite view: it's rather clunky and duplicative. It appears to take the text of every `a` element and add an entry. If we link to definitions and sections using the same words, we get different entries, although nothing makes clear which is which until you follow the link into the body and then click on that link to see where it goes.

Here's a random sampling I spotted in the RS spec only looking at a few "p" entries:

```
- package document
- package document
...
- properties
- properties attribute
- properties attribute
...
- publication resources
- publication resources
```

**Comment by mattgarrish** [comment]
I'm opting for a middle road on this and adding indexes to the three rec-track specs but removing the CSS link overrides so we have consistent colouring of our links.

**Pull request merged**
