### PR TITLE
Added the SVG reference and some notes for CSS restrictions

### PR DESCRIPTION
**Pull request by iherman**
This is a PR for #1614 (and for the corresponding [WG resolution](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-04-08-epub#resolution2)).

- Added a reference to the SVG `direction` attribute (to be used instead of the CSS `direction` property). I had to rephrase the bullet item texts to make it a bit more readable
- Added a note for the background of these restrictions
- Added a note in the RS document that RS-s can "do what they damn well please" :-)

One discrepancy I encountered is that there seems to be no equivalent to a `bidi` element in SVG2. Ie, the restriction on the  `unicode-bidi` CSS property does not apply to SVG2.

(I may have misunderstood something. Maybe @fantasai can help out on this.)

* For Preview  on the EPUB 3.3 Reading Systems:
    * [Preview](https://raw.githack.com/w3c/epub-specs/css-dir-property-issue-1614/epub33/rs/index.html)
    * [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://w3c.github.io/epub-specs/epub33/rs/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/w3c/epub-specs/css-dir-property-issue-1614/epub33/rs/index.html)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/pull/1627.html" title="Last updated on Apr 16, 2021, 5:29 PM UTC (55a0733)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/1627/edb9e7b...55a0733.html" title="Last updated on Apr 16, 2021, 5:29 PM UTC (55a0733)">Diff</a>

### CODE REVIEW

**Comment by mattgarrish** [comment]
> One discrepancy I encountered is that there seems to be no equivalent to a `bidi` element in SVG2. Ie, the restriction on the `unicode-bidi` CSS property does not apply to SVG2.

The SVG `unicode-bidi` attribute maps to the CSS property, so why would it be appropriate to use CSS instead of the attribute?

That HTML also has a `bdo` element doesn't appear of consequence.

**Comment by mattgarrish** [comment]
I think we should state more generally that authoring restrictions are not applicable to reading systems, as the CSS properties are only one case of restrictions we impose on HTML, MathML, SVG, etc.

I was thinking after the call we should probably have a statement more like the following somewhere:

> The definition of EPUB Content Documents includes various authoring restrictions to optimize the cross-compatibility of content (e.g., prohibiting CSS for setting language and direction). **Unless stated otherwise in this specification, Reading Systems MAY support these restricted features.**

(Bolding's sort of a polite way of screaming to do what you please.)

Maybe this could float at the start of the content documents section, or maybe it would be better to incorporate into a section on authoring restrictions?

**Comment by iherman** [comment]
> > One discrepancy I encountered is that there seems to be no equivalent to a `bidi` element in SVG2. Ie, the restriction on the `unicode-bidi` CSS property does not apply to SVG2.
> 
> The SVG `unicode-bidi` attribute maps to the CSS property, so why would it be appropriate to use CSS instead of the attribute?
> 

There is something strange happening that I do not understand. I see no _definition_ for the `unicode-bidi` property in SVG. It is used in an example and in the text in [the section on direction](https://www.w3.org/TR/SVG2/text.html#DirectionProperty) but it all refers to the CSS spec only.

Is our requirement for the SVG case something like:

>   It MUST NOT use the unicode-bidi property [CSS-Writing-Modes-3] for [SVG] Content Documents. Use the [SVG] unicode-bidi and direction attributes to control bidirectionality.

Knowing that I _cannot_ put a normative reference to an SVG reference to the `unicode-bidi` attribute but only to the CSS property definition? This is what bothered me...

I may miss something fundamental...

**Comment by iherman** [comment]
> I think we should state more generally that authoring restrictions are not applicable to reading systems, as the CSS properties are only one case of restrictions we impose on HTML, MathML, SVG, etc.
> 
> I was thinking after the call we should probably have a statement more like the following somewhere:
> 
> > The definition of EPUB Content Documents includes various authoring restrictions to optimize the cross-compatibility of content (e.g., prohibiting CSS for setting language and direction). **Unless stated otherwise in this specification, Reading Systems MAY support these restricted features.**
> 
> (Bolding's sort of a polite way of screaming to do what you please.)
> 
> Maybe this could float at the start of the content documents section, or maybe it would be better to incorporate into a section on authoring restrictions?

I actually like that, is it more future proof. It may be put into [§4](http://localhost:8001/LocalData/github/EPUB/epub-specs/epub33/rs/#sec-contentdocs) _before_ §4.1.

**Comment by iherman** [comment]
@mattgarrish, I have adopted your proposed change in https://github.com/w3c/epub-specs/pull/1627/commits/dd58c5037a0194b59b6348939c5b8e5c937a72f3. However, I have not used the boldface; I do not think we use that type of typesetting trick elsewhere in the document, so it looked a bit out of place…

**Comment by mattgarrish** [comment]
> I see no _definition_ for the `unicode-bidi` property in SVG. It is used in an example and in the text in [the section on direction](https://www.w3.org/TR/SVG2/text.html#DirectionProperty) but it all refers to the CSS spec only.

Right, the formal process of using css properties as attributes is defined under "[presentation attributes](https://www.w3.org/TR/SVG2/styling.html#PresentationAttributes)".

For all the listed CSS properties there are equivalent svg attributes. The attribute are exact mappings to the css properties, which is why I don't believe we need to worry about `bdo`. That's for html which doesn't have this equivalency.

That's why they just talk about the "property" but then use it as an attribute. You could always link to the presentation attribute section, I suppose, as someone can find their way from there to the definition.

**Comment by mattgarrish** [comment]
> I have not used the boldface; I do not think we use that type of typesetting trick elsewhere in the document

Oh, come on, take a walk on the wild side... :)

([Never say never](https://www.w3.org/TR/epub-33/#sec-docs-assoc-style)... although I thought we had more.)

**Comment by iherman** [comment]
On the SVG bi-di stuff: here is what I have just committed for that item:

> It MUST NOT use the <a href="https://www.w3.org/TR/css3-writing-modes/#unicode-bidi"><code>unicode-bidi</code> property</a> [[!CSS-Writing-Modes-3]] for [[!SVG]] Content Documents. Use the [[!SVG]] <a href="https://www.w3.org/TR/SVG2/styling.html#PresentationAttributes">presentation attribute alternative</a> for <code>unicode-bidi</code> and the <a href="https://www.w3.org/TR/SVG2/text.html#DirectionProperty"><code>direction</code> attribute</a> to control bidirectionality.

How does that sound?

**Comment by iherman** [comment]
> Oh, come on, take a walk on the wild side... :)

O.k., you win :-)

**Review by mattgarrish — APPROVED** [review]

**Comment by iherman** [comment]
@mattgarrish I have finalized the stuff (essentially rolling back my last commit and modifying a little bit the note you provided).

**Comment by iherman** [comment]
@dauwhe @wareid could you look at this? It would be time to merge (also trying to avoid complex merge conflicts...)

**Review by wareid — APPROVED** [review]

**Pull request merged**
