### PR TITLE
remove requirement to support SVG requiredExtensions attribute per #1087

### PR DESCRIPTION
**Pull request by dauwhe**
***
<a href="https://pr-preview.s3.amazonaws.com/dauwhe/epub-specs/pull/1662.html" title="Last updated on May 4, 2021, 5:01 PM UTC (49b5dab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/1662/010a52f...dauwhe:49b5dab.html" title="Last updated on May 4, 2021, 5:01 PM UTC (49b5dab)">Diff</a>

### CODE REVIEW

**Review by iherman — APPROVED** [review]

**Review by iherman — APPROVED** [review]
I believe this change should be recorded in the changes' section.

**Comment by mattgarrish** [comment]
Fine with this change (except needs a change entry as already noted), but are authors still required to set the attribute or are we dropping that requirement, too?

**Comment by iherman** [comment]
> Fine with this change (except needs a change entry as already noted), but are authors still required to set the attribute or are we dropping that requirement, too?

Looking up the original issues it seems that this attribute does more harm than good; [my own tests](https://github.com/w3c/epub-specs/issues/1087#issuecomment-718880480) resulted in SVG content that was not displayed (eg, on Thorium). So yes, I believe authors should forget about this.

**Comment by dauwhe** [comment]
I removed the corresponding line from the core spec, and added an entry to the change log.

**Review by mattgarrish — APPROVED** [review]

**Pull request merged**
