### PR TITLE
Require Unicode full case folding and NFC normalization

### LINKED ISSUE #1631: Case folding of the file names
https://w3c.github.io/epub-specs/epub33/core/#sec-container-filenames

>   All File Names within the same directory MUST be unique following case normalization as described in section 3.13 of [Unicode].

This sentence does not seem to be very clear. Would you please clarify what algorithm of "case normalization" is used here? Is it Unicode full or simple casefolding?

Please refer to <a href="https://www.w3.org/TR/charmod-norm/#definitionCaseFolding">Case Mapping and Case Folding</a> and <a href="https://www.w3.org/TR/charmod-norm/#handlingCaseFolding">Additional Considerations for Case Folding</a> in [charmod-norm](https://www.w3.org/TR/charmod-norm/).

### PR DESCRIPTION
**Pull request by mattgarrish**
Includes an informative reference to charmod-norm for more information.

Fixes #1631

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/pull/1648.html" title="Last updated on Apr 27, 2021, 3:16 PM UTC (2de6c13)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/1648/3b68534...2de6c13.html" title="Last updated on Apr 27, 2021, 3:16 PM UTC (2de6c13)">Diff</a>

### CODE REVIEW

**Review by iherman — CHANGES_REQUESTED** [review]
That may be a respec bug, but the charmod reference is put into the list of _normative_ references! It may be that the "note" part has to be put into an explicit note to make the reference informative...

**Comment by mattgarrish** [comment]
Looks like they changed respec so you don't use exclamation points at all now. To override a reference in a normative section and make it informative you use ?. See https://respec.org/docs/#references

**Comment by iherman** [comment]
> Looks like they changed respec so you don't use exclamation points at all now. To override a reference in a normative section and make it informative you use ?. See https://respec.org/docs/#references

Wow. I did not realize this!

**Comment by mattgarrish** [comment]
Ya, I'm sure it's broken other references we have. I've fixed the three in this PR for now, but will do a more thorough check of all the specs and clean them up again.

**Comment by iherman** [comment]
Sigh. I do not like such backward compatible changes. Oh well... let that be the fight of somebody else...

**Review by iherman — APPROVED** [review]

**Comment by xfq** [comment]
Glad to see that you have referred to charmod-norm. It would be useful to mention the order of Unicode normalization and Unicode full case folding, i.e., normalization should precede case folding.

(Related PR in charmod-norm: https://github.com/w3c/charmod-norm/pull/215)

**Comment by iherman** [comment]
@xfq the text now says (in #1680, that is): 

> All File Names within the same directory MUST be unique following NFC normalization [[TR15]] and then case folding [[Unicode]].

(followed by the charmod reference, of course). Is that o.k.?

**Comment by xfq** [comment]
@iherman The current text says:

>   All File Names within the same directory MUST be unique following NFC normalization [TR15] and then full case folding [Unicode].

i18n WG discussed this in teleconference and I drew the action to respond here. We don't think it is necessary to mention NFC in the requirement. If you want to refer to charmod-norm normatively, you can refer to [Unicode Canonical Case Fold Normalization Step](https://w3c.github.io/charmod-norm/#CanonicalFoldNormalizationStep).

If you want to refer to Unicode and [UAX #15](https://www.unicode.org/reports/tr15/) normatively, you can change "NFC normalization" to "Unicode normalization" (or to "NFC or NFD normalization") so the spec won't limit people to NFC.

**Comment by iherman** [comment]
@xfq I have created #1692 to handle this. The full paragraph now says:

```html
<p id="ocf-fn-cn">All File Names within the same directory MUST be unique following Unicode 
normalization [[UAX15]] and then full case folding [[Unicode]]. (Refer to 
<a href="https://www.w3.org/TR/charmod-norm/#CanonicalFoldNormalizationStep">Unicode 
Canonical Case Fold Normalization Step</a> [[?CHARMOD-NORM]] for more information.)</p>
```

Can you approve or comment on #1692? Thx.

**Comment by aphillips** [comment]
One small addendum. There are four types of Unicode normalization: two canonical normalization forms (NFC/NFD) and two compatibility forms (NFKC/NFKD). You do not intend the Kompatibility forms to be used here, so I would at least say "Unicode canonical normalization".

**Comment by iherman** [comment]
> One small addendum. There are four types of Unicode normalization: two canonical normalization forms (NFC/NFD) and two compatibility forms (NFKC/NFKD). You do not intend the Kompatibility forms to be used here, so I would at least say "Unicode canonical normalization".

Done.

**Pull request merged**
