### PR TITLE
Add technique for media overlays and access modes

### LINKED ISSUE #2303: Media overlays in accessMode declarations
As I mentioned in a [mailing list comment](https://lists.w3.org/Archives/Public/public-epub-wg/2022May/0024.html):

> EPUB’s media overlays feature means you could have a sufficient auditory pathway. Media overlays are not how the information is encoded or required to be played by default, so I wouldn’t expect the publisher to list auditory as an access mode based solely on their presence. But they do provide you an auditory playback option provided the complete text is narrated (i.e., they’re more like an affordance).

Full text books with media overlays are not audiobooks as we know them, so saying there is an audio requirement is misleading to me. I would only list auditory as an accessMode when you have to turn on media overlays to get the full information of the book (i.e., when they're more like DAISY audio books with minimal text for chapter navigation).

Whatever we ultimately resolve here should also be noted in the techniques (and other places like the DAISY KB).

/cc @madeleinerothberg

### PR DESCRIPTION
**Pull request by mattgarrish**
I've added a new technique to discuss the two cases for media overlays I'm aware of -- full text with full audio and structured audio. For full text with audio, the recommendation is to not set an auditory access mode and instead indicate the synchronizedAudioText feature. For structured audio, you do the opposite and set an auditory access mode and don't set synchronizedAudioText.

Let me know what you all think of this guidance.

Fixes #2303

EPUB Accessibility Techniques 1.1:
- [Preview](https://raw.githack.com/w3c/epub-specs/a11y/issue-2303/epub33/a11y-tech/index.html)
- [Diff](https://services.w3.org/htmldiff?doc1=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://w3c.github.io/epub-specs/epub33/a11y-tech/index.html&doc2=https://labs.w3.org/spec-generator/%3Ftype=respec%26url=https://raw.githack.com/w3c/epub-specs/a11y/issue-2303/epub33/a11y-tech/index.html)

### CODE REVIEW

**Review by clapierre — COMMENTED** [review]
These two statements seem to conflict with each other.

				<p>For example, a publication with media overlays that has text and images (with text alternatives)
						would only declare the following sufficient access modes: "<code>textual</code>",
							"<code>auditory</code>, and "<code>textual,visual</code>".</p>

					<p>It would <strong>not</strong> declare: "<code>textual</code>", "<code>auditory</code>",
							"<code>textual,auditory</code>", "<code>textual,visual</code>", and
							"<code>textual,visual,auditory</code>".</p>

Shouldn't it only have "NOT" "<code>textual,visual,auditory</code>" ?

**Comment by mattgarrish** [comment]
It would also omit "textual,auditory" since that implies switching back and forth between the two.

But I agree it might be simpler to list the two that are not declared than show both complete sets.

**Review by clapierre — APPROVED** [review]

**Comment by madeleinerothberg** [comment]
Agree it would be clearer to only show the omitted items in the NOT list.

>It would also omit "textual,auditory" since that implies switching back and forth between the two.

I don't fully understand media overlays. Is it not possible to listen while looking at the text? In that case, yes, that combo would also be omitted.

A separate comment: the text says
>Likewise, since the text in the publication only provides heading navigation, EPUB creators will not list a textual access mode. The user does not need to, and is not expected to, visually read this text.

In this case, it isn't only that the user doesn't need to or isn't expected to read the text (assuming they can listen straight through with pause/play, if they can't read the TOC structure). They actually **can't** visually read the text because it isn't there.

**Comment by mattgarrish** [comment]
> Is it not possible to listen while looking at the text? In that case, yes, that combo would also be omitted.

It's up to the user. If they want to read along with the narration, the text will be highlighted. But you can also use media overlays to switch back and forth between visual and auditory reading. The typically example is listening to audio while commuting but reading visually elsewhere. So in that sense there is a pathway that is both textual and auditory, but I don't think it's a case we need to highlight.

> They actually **can't** visually read the text because it isn't there.

There always has to be some text to synchronize with for media overlays. In the structured navigation case, you'd just get a list of all the headings in the viewport, with each one being highlighted in turn (assuming your device has a viewport). So there is technically _some_ of the textual content of the book there, but it's entirely useless as far as visual reading goes.

**Comment by mattgarrish** [comment]
This one's also been open for a couple of weeks now without any new change requests. I'm going to merge it since it's only a technique and we can easily change it if new issues come up.

**Pull request merged**
