### PR TITLE
Fixing issue in 1611

### LINKED ISSUE #1611: OPTIONAL should not be capitalized in epubReadingSystem.hasFeature()
https://w3c.github.io/epub-specs/epub33/rs/#app-ers-hasFeature-desc says `The OPTIONAL `version` parameter is included for querying custom features that could change in incompatible ways over time. The return value indicates support only for the specified version of the feature.`

But this is referring to optionality from the caller's perspective, not the implementer's perspective. I believe that all-caps OPTIONAL should be reserved for features that a Reading System may or may not implement; in this case, I believe the Reading System MUST implement the `version` parameter, and an EPUB author may or may not use the parameter.

Therefore (assuming my understanding is correct), I think OPTIONAL should not be capitalized in this case.

### PR DESCRIPTION
**Pull request by iherman**
Turning terms into lower case, see #1611.

Fix #1611

### CODE REVIEW

**Review by dlazin — APPROVED** [review]

**Comment by mattgarrish** [comment]
Sorry, this is unfortunately a bigger problem than this PR gets into.

A quick recap is that there was no easy way to break up this section at the time I was pulling the reading system requirements out from the content, so I took the lazy route and brought it all over to the RS spec since there were far fewer authoring requirements embedded.

We also have the lingering questions of whether this interface should be deprecated or made informative to address. I was sort of hoping the whole section would go away before having to figure out what to do with the authoring statements... :)

So the solution could be
- keeping the interface and finding some way of writing the requirements into the authoring specification
- making the interface informative, in which case all normative keywords can go away
- deprecating the interface and dropping the section except for a link back to 3.2 where it would be last defined

**Comment by iherman** [comment]
> Sorry, this is unfortunately a bigger problem than this PR gets into.

Indeed, this is https://github.com/w3c/epub-specs/issues/1420 which I referred to from in #1610. But (although I did not produce a PR for #1610 yet) I tend to agree with the comment of @dlazin in https://github.com/w3c/epub-specs/issues/1610#issuecomment-814298887 that making this change is easy, we can at least improve what is already there and come back to #1420 at some point (which we will have to do).

**Comment by mattgarrish** [comment]
Can we at least drop "EPUB Creators" from the sentence?

I'd find this less problematic if it didn't bring in creators at all:

> Features defined in this specification are considered versionless. If a Reading System supports a feature defined in this specification, it MUST ignore any supplied version parameter and return a true value.

**Comment by iherman** [comment]
> 
> I'd find this less problematic if it didn't bring in creators at all:
> 
> > Features defined in this specification are considered versionless. If a Reading System supports a feature defined in this specification, it MUST ignore any supplied version parameter and return a true value.

I have made the change.

**Pull request merged**
