### PR TITLE
Media type registrations are normative

### LINKED ISSUE #2313: Should media type registration be normative?
Per https://www.w3.org/2020/01/registering-mediatypes , media type registration should be a normative part of a specification, but [Media type registrations](https://w3c.github.io/epub-specs/epub33/core/#app-media-types) in EPUB is currently non-normative. Is that intentional?

### PR DESCRIPTION
**Pull request by iherman**
This is a PR for the branch behind #2297 in view of a CRS publication.

Fix #2313

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 7, 2022, 1:35 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fepub-specs%2F37179bf137e43ef78b88240b3f7ad85cdac5674b%2Fepub33%2Fcore%2Findex.html%3FisPreview%3Dtrue)

```

😭  Sorry, there was an error generating the HTML. Please report this issue!
Specification: http://labs.w3.org/spec-generator/uploads/fttDRc?isPreview=true&publishDate=2022-06-07
ReSpec version: 32.1.8
File a bug: https://github.com/w3c/respec/
Error: Error: Evaluation failed: Timeout: document.respec.ready didn't resolve in 27664ms.
    at ExecutionContext._evaluateInternal (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/u/spec-generator/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async generateHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:221:12)
    at async toHTML (/u/spec-generator/node_modules/respec/tools/respecDocWriter.js:92:18)
    at async Object.generate [as respec] (file:///u/spec-generator/generators/respec.js:15:44)
    at async file:///u/spec-generator/server.js:247:48

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/epub-specs%232325.)._
</details>

### CODE REVIEW

**Review by mattgarrish — APPROVED** [review]

**Comment by mattgarrish** [comment]
Note that the auto-close on #2313 won't work when you merge into a branch (it's not shown as linked in the issues list). You'd need to mention it from #2297.

Do we want to close #2313 with this update, though, or leave it open until the IANA registration is closed?

**Comment by iherman** [comment]
Let us merge/close it. The IANA registration (more exactly, modification) is a different issue.

**Comment by iherman** [comment]
@mattgarrish should we change this PR so that it patches the 'main' branch rather than #2297? By doing so, we can merge #2297 at once (we have the green light of the WG as well as PlH's). Just to clean up the PR-s...

**Comment by mattgarrish** [comment]
I've switched it to integrate with main now. It's showing the commits for #2297, but after I merge that one I should be able to merge main back in here to clean it up.

**Pull request merged**
