### PR TITLE
Attempt to fix #1299 by adding some text to CMT about track element not requiring a fallback

### LINKED ISSUE #1299: text/vtt as core media type?
I did not see text/vtt listed as a core media type but it is the required subtitle format for the html5 video tag if subtitles are provided, as they should be for video content.

### PR DESCRIPTION
**Pull request by dauwhe**
#1299 asked for some clarification on this.

***
<a href="https://pr-preview.s3.amazonaws.com/dauwhe/epub-specs/pull/1657.html" title="Last updated on May 3, 2021, 9:47 PM UTC (59a8ac2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/epub-specs/1657/1a90e58...dauwhe:59a8ac2.html" title="Last updated on May 3, 2021, 9:47 PM UTC (59a8ac2)">Diff</a>

### CODE REVIEW

**Comment by mattgarrish** [comment]
We might want to make the statement more general to cover all possibilities:

"Caption, subtitle, description and other formats that EPUB Creators can express in the video `track` element are similarly not Core Media Types but do not require fallbacks. Refer to `<a href="#sec-xhtml-fallbacks"></a>` for more information."

**Comment by mattgarrish** [comment]
Forgot to include webvtt in the text, so maybe more like:

"EPUB Creators may similarly include captions, subtitles, descriptions and other formats in the video `track` element without fallbacks. For example, they may use [[WebVTT]] to express many types of tracks. Refer to `<a href="#sec-xhtml-fallbacks"></a>` for more information."

**Comment by dauwhe** [comment]
@mattgarrish are file formats besides VTT used with the track element?

**Comment by mattgarrish** [comment]
> are file formats besides VTT used with the track element?

TTML used to possible. I assume it's still usable even if it's probably lost the war by now.

There's also the chapters type. I don't know if there's a standard format for it.

But given the open-ended nature of the element, I don't know if we could say there's only one format that can be used with it.

**Comment by mattgarrish** [comment]
What still bothers me is the focus on the track element. It sounds like a repeat of the foreign resource restriction exemption that we already define in https://w3c.github.io/epub-specs/epub33/core/#sec-xhtml-fallbacks

You can also specify tracks for the audio element, so if we need to keep something in the CMT table perhaps we should think about adding a dedicated section to the table?

If so, I'd still favour formatting it like the note we have for fonts with less emphasis on the element:

| Media Type ... |
|-------------| 
| ... |
| Tracks |
| EPUB 3 allows EPUB Creators to include any type of audio or video track (e.g., [[?WebVTT]] captions, subtitles and descriptions) without a fallback. Refer to `<a href="#sec-xhtml-fallbacks"></a>` for more information. |

(Sorry for being a PITA on this!)

**Comment by dauwhe** [comment]
@mattgarrish updated per your comment. Please, please never stop being a PITA! ;)

**Review by mattgarrish — APPROVED** [review]

**Pull request merged**
